networks:
  oosuite:

services:
  nginx:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www:delegated
    depends_on:
      - php
      - redis
      - mysql
      - mailhog
    networks:
      - oosuite

  mysql:
    image: mariadb
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./www/html:/var/www/html:delegated
    environment:
      MYSQL_DATABASE: oosuite
      MYSQL_USER: oosuite
      MYSQL_PASSWORD: Mark053
      MYSQL_ROOT_PASSWORD: Mark053
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - oosuite

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "9000:9000"
    volumes:
      - ./www:/var/www:delegated
    networks:
      - oosuite

  redis:
    image: redis:7.2.4-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./www/html:/var/www/html:delegated
    networks:
      - oosuite
