networks:
  oosuite:

services:
  nginx:
    build:
      context: ./conf
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx/:/etc/nginx/conf.d/:delegated
      - ./wwwroot:/var/www:delegated
    depends_on:
      - php
      - redis
      - mysql
    networks:
      - oosuite

  mysql:
    image: mariadb
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./wwwdb:/var/lib/mysql
      - ./wwwroot/htdocs:/var/www/htdocs:delegated
    environment:
      MYSQL_DATABASE: oosuite
      MYSQL_USER: oosuite
      MYSQL_PASSWORD: Mark053
      MYSQL_ROOT_PASSWORD: Mark053
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - oosuite

  php:
    build:
      context: ./conf
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "9000:9000"
    volumes:
      - ./wwwroot:/var/www:delegated
    networks:
      - oosuite

  redis:
    image: redis:7.2.4-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./wwwroot/htdocs:/var/www/htdocs:delegated
    networks:
      - oosuite
