networks:
  vpc:

services:
  nginx:
    image: nginx:1.26.0
    ports:
      - "80:80"
    container_name: nginx
    volumes:
      - ./conf/nginx:/etc/nginx
      - ./log/nginx:/var/log/nginx
      - ./wwwroot:/var/www
    depends_on:
      - php
      - redis
      - mysql
    restart: unless-stopped
    networks:
      - vpc

  mysql:
    image: mysql:8.4.0
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    container_name: mysql
    volumes:
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf
      - ./log/mysql:/var/log/mysql
      - ./wwwdb:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: oosuite
      MYSQL_USER: oosuite
      MYSQL_PASSWORD: Mark053
      MYSQL_ROOT_PASSWORD: Mark053
    networks:
      - vpc

  php:
    build:
      context: ./conf
      dockerfile: php.dockerfile
    restart: unless-stopped
    ports:
      - "9000:9000"
    container_name: php
    volumes:
      - ./conf/php:/usr/local/etc/php-fpm.d
      - ./log/php:/var/log/php
      - ./wwwroot:/var/www
    networks:
      - vpc

  redis:
    image: redis:7.2.4
    restart: unless-stopped
    ports:
      - "6379:6379"
    container_name: redis
    volumes:
      # - ./conf/redis:/usr/local/etc/redis
      - ./log/redis:/var/log/redis
    networks:
      - vpc
