# docker-compose 常见命令

# docker --version #查看版本
# docker-compose -h    # 查看帮助
# docker-compose up    # 启动所有docker-compose服务
# docker-compose up -d    # 启动所有docker-compose服务并后台运行
# docker-compose down     # 停止并删除容器、网络、卷、镜像。
# docker-compose exec 服务id   # 进入容器实例内部
# docker-compose exec 服务id /bin/bash
# docker-compose ps      # 展示当前docker-compose编排过的运行的所有容器
# docker-compose top       # 展示当前docker-compose编排过的容器进程
# docker-compose logs 服务id   # 查看容器输出日志
# docker-compose config     # 检查配置
# docker-compose config -q  # 检查配置，有问题才有输出
# docker-compose restart   # 重启服务
# docker-compose start     # 启动服务
# docker-compose stop      # 停止服务

networks:
  vpc:

services:
  nginx:
    image: nginx:1.26.0
    ports:
      - "80:80"
    container_name: nginx
    volumes:
      - ./conf/nginx:/etc/nginx
      - ./log/nginx:/var/log/nginx
      - ./wwwroot:/var/www
    depends_on:
      - php
      - redis
      - mysql
    restart: unless-stopped
    networks:
      - vpc

  mysql:
    image: mysql:8.4.0
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    container_name: mysql
    volumes:
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf
      - ./log/mysql:/var/log/mysql
      - ./wwwdb:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: oosuite
      MYSQL_USER: oosuite
      MYSQL_PASSWORD: Mark053
      MYSQL_ROOT_PASSWORD: Mark053
    networks:
      - vpc

  php:
    build:
      context: ./conf
      dockerfile: php.dockerfile
    restart: unless-stopped
    ports:
      - "9000:9000"
    container_name: php
    volumes:
      - ./conf/php:/usr/local/etc/php-fpm.d
      - ./log/php:/var/log/php
      - ./conf/root:/root
      - ./wwwroot:/var/www
    networks:
      - vpc

  redis:
    image: redis:7.2.4
    restart: unless-stopped
    ports:
      - "6379:6379"
    container_name: redis
    volumes:
      # - ./conf/redis:/usr/local/etc/redis
      - ./log/redis:/var/log/redis
    networks:
      - vpc
